language: php
php:
  - '7.3'

before_script:
  - composer require php
  - composer require cakephp/cakephp

# safelist
branches:
  only:
    - master
    - stable

notifications:
  email:
    - contact@aymardkouakou.me