
language: php

php:
  - '7.3'

before_install:
  - composer self-update

install:
  - composer require php
  - composer require cakephp/cakephp

branches:
  only:
    - master

notifications:
  email: false